---
title: "Simulation for the entropy balancing method"
author: "Maciej Beręsewicz"
format: 
  html:
    self-contained: true
    table-of-contents: true
    number-sections: true
    df-print: kable
editor: source
execute: 
  eval: true
  warning: false
  message: false
toc-title: Contents
lang: en
---

# Load packages

Packages and options for `xtable`.

```{r}
library(data.table)
library(ggplot2)
library(xtable)
library(stringr)
library(glue)
options(xtable.include.rownames = FALSE)
```

# Result for the simulation 1 -- entropy balancing

```{r}
sim1_results <- readRDS("../results/sim1-ebal-updated.rds")
sim1_results[is.na(tau), est_p := est]
sim1_results[!is.na(tau), est_p := paste0(est, " (", str_pad(tau,4,"right", "0"), ")")]
sim1_results[, est_p:=factor(est_p, 
                             c("balance", "att", "qtt (0.10)", "qtt (0.25)", "qtt (0.50)", "qtt (0.75)", "qtt (0.90)"),
                             c("bal", "ATT", "QTT (0.10)", "QTT (0.25)", "QTT (0.50)", "QTT (0.75)", "QTT (0.90)"))]

sim1_results[, method:=str_remove(method, "w_")]

sim1_results[, method_l:=factor(method, c("ebal", "kbal", "deb1", "deb2"), c("EB", "KEB", "DEB MQ", "DEB MD"))]
```

Table 1

```{r}
sim1_results[var == "y3" & est_p != "bal", 
             .(Bias = mean(treat), Var = var(treat), RMSE = sqrt(mean(treat)^2 + var(treat))),
             .(design, est_p, method_l)] |> 
  melt(id.vars = c("design", "est_p", "method_l")) |> 
  dcast(variable + method_l + design ~ est_p, value.var = "value") |> 
  {\(x) x[order(design, variable, method_l)]}() |>
  ## uncomment for xtable
  transform(design = NULL) #|>
  #xtable(digits = 4)
```

Balance and ESS

```{r}
sim1_results[est_p == "bal", .(rep,design, method_l, x1,x2,x3,x4,x5,x6,ess)] |>
  melt(id.vars = c("rep", "design", "method_l")) |>
  aggregate(value ~ variable + design + method_l, data = _, FUN = mean) |>
  transform(value = ifelse(variable != "ess", value*100, value)) |>
  dcast(data=_, design + method_l ~ variable, value.var = "value") |>
  xtable()
```


```{r}
sim1_results[est_p == "bal", .(rep,design, method_l, x1,x2,x3,x4,x5,x6,ess)] |>
  melt(id.vars = c("rep", "design", "method_l")) |>
  subset(variable != "ess") |>
  ggplot(data = _, aes(x = method_l, y = value)) +
  geom_boxplot() +
  facet_grid(design~variable)

sim1_results[est_p == "bal", .(rep,design, method_l, x1,x2,x3,x4,x5,x6,ess)] |>
  melt(id.vars = c("rep", "design", "method_l")) |>
  subset(variable == "ess") |>
  ggplot(data = _, aes(x = method_l, y = value)) +
  geom_jitter(alpha=0.1) + 
  geom_boxplot() +
  facet_grid(variable~design)

```

Table A1 in Appendix

```{r}
sim1_results[var == "y1" & est_p != "bal", 
             .(Bias = mean(treat), Var = var(treat), RMSE = sqrt(mean(treat)^2 + var(treat))),
             .(design, est_p, method_l)] |> 
  melt(id.vars = c("design", "est_p", "method_l")) |> 
  dcast(variable + method_l + design ~ est_p, value.var = "value") |> 
  {\(x) x[order(design, variable, method_l)]}() |>
  ## uncomment for xtable
  transform(design = NULL) #|>
  #xtable(digits = 4)
```

Table A2 in the Appendix

```{r}
sim1_results[var == "y2" & est_p != "bal", 
             .(Bias = mean(treat), Var = var(treat), RMSE = sqrt(mean(treat)^2 + var(treat))),
             .(design, est_p, method_l)] |> 
  melt(id.vars = c("design", "est_p", "method_l")) |> 
  dcast(variable + method_l + design ~ est_p, value.var = "value") |> 
  {\(x) x[order(design, variable, method_l)]}() |>
  ## uncomment for xtable
  transform(design = NULL) #|>
  #xtable(digits = 4)
```

Additional plots

```{r}
for (des in c("d1", "d2", "d3")) {
  sim1_results[est_p != "bal", .(Bias = mean(treat), SE = sd(treat), RMSE = sqrt(mean(treat)^2 + var(treat))),
             .(design, est_p, method_l, var)] |> 
      melt(id.vars = c("design", "est_p", "method_l", "var")) |> 
      subset(design == des) |> 
      ggplot(data = _, aes(x = est_p, y = value, fill = method_l)) +
      geom_col(position = "dodge", color = "black") +
      facet_grid(var ~ variable , scales = "free", 
                 labeller = labeller(var = c("y1"="Y1\nlinear",
                                             "y2"="Y2\nmedium non-lin",
                                             "y3"="Y3\nstrong non-lin"))) +
      scale_fill_brewer(type = "qual", palette = "Set1") +
      theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1)) +
      labs(x = "Causal parameter", y = "Values (note different scales)", fill = "Estimator")
  ggsave(filename = glue("../results/fig-sim-1-ebal-{des}.png"), width = 7, height = 5)
}

```

Boxplots

```{r}
sim1_results[est_p != "bal"] |> 
  ggplot(data = _, aes(x = est_p, y = treat, color = method_l)) +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_boxplot(outlier.size = 0.5, size = 0.3) +
  facet_grid(var ~ design, scale = "free_y",
             labeller = labeller(var = c("y1"="Y1 (linear)", 
                                         "y2"="Y2 (weak non-lin)",
                                         "y3"="Y3 (stron non-lin)"),
                                 design = c("d1"="D1 (strong sep, norm)",
                                            "d2"="D2 (weak sep, norm)",
                                            "d3"="D3 (medium sep, lep)"))) +
  scale_color_brewer(type = "qual", palette = "Set1") +
  labs(x = "Causal parameter", y = "Value", color = "Method") +
  theme(axis.text.x = element_text(angle = 45, vjust=1,hjust=1)) -> p1

ggsave(plot = p1, filename = glue("../results/fig-sim-1-ebal-boxplot.png"), width = 7, height = 5)
```

# Result for the simulation 1 -- Propensity score

```{r}
sim1 <- readRDS("../results/sim2-dgp1-1000.rds")
sim2 <- readRDS("../results/sim2-dgp2-1000.rds")
```

Table 2 

```{r}
sim2$ATE |> 
  melt(id.var = "id") |> 
  setDT() |> 
  {\(x) x[, .(Bias = mean(value)-10, Var = var(value), RMSE = sqrt( (mean(value)-10)^2 + var(value))), .(est=variable)]}() |> 
  transform(quant = "ATE") |> 
  rbind(sim2$QTE[, .(Bias = mean(value)-10, Var = var(value), RMSE = sqrt( (mean(value)-10)^2 + var(value))), 
                 .(est, quant = factor(quant, 1:5, c("0.10", "0.25", "0.50", "0.75", "0.90")))] ) |> 
  melt(id.vars = c("est", "quant")) |> 
  transform(quant = factor(quant, 
                           c("ATE", "0.10", "0.25", "0.50", "0.75", "0.90"),
                           c("ATE", "QTE(0.10)", "QTE(0.25)", "QTE(0.50)", "QTE(0.75)", "QTE(0.90)")),
            est = factor(est,
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CPBS (e)", "CBPS (e MQ)", "CBPS (e MP)", "CPBS (e P)", 
                           "CBPS (o)", "CBPS (o MQ)", "CBPS (o MP)", "CPBS (o P)"),
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CBPS (e)", "DPS (e MQ)", "DPS (e MD)", "DPS (e D)", 
                           "CBPS (o)", "DPS (o MQ)", "DPS (o MD)", "DPS (o D)"))) -> sim2_results2

sim2_results2 |>
  dcast(variable + est ~ quant, value.var = "value") |>
  # uncomment for xtable
  subset(select = -variable) #|> 
  #xtable(digits = 4) 
  
```

Table A3 in the Appendix

```{r}
sim1$ATE |> 
  melt(id.var = "id") |> 
  setDT() |> 
  {\(x) x[, .(Bias = mean(value)-10, Var = var(value), RMSE = sqrt( (mean(value)-10)^2 + var(value))), .(est=variable)]}() |> 
  transform(quant = "ATE") |> 
  rbind(sim1$QTE[, .(Bias = mean(value)-10, Var = var(value), RMSE = sqrt( (mean(value)-10)^2 + var(value))), 
                 .(est, quant = factor(quant, 1:5, c("0.10", "0.25", "0.50", "0.75", "0.90")))] ) |> 
  melt(id.vars = c("est", "quant")) |> 
  transform(quant = factor(quant, 
                           c("ATE", "0.10", "0.25", "0.50", "0.75", "0.90"),
                           c("ATE", "QTE(0.10)", "QTE(0.25)", "QTE(0.50)", "QTE(0.75)", "QTE(0.90)")),
            est = factor(est,
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CPBS (e)", "CBPS (e MQ)", "CBPS (e MP)", "CPBS (e P)", 
                           "CBPS (o)", "CBPS (o MQ)", "CBPS (o MP)", "CPBS (o P)"),
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CBPS (e)", "DPS (e MQ)", "DPS (e MD)", "DPS (e D)", 
                           "CBPS (o)", "DPS (o MQ)", "DPS (o MD)", "DPS (o D)")))-> sim2_results1

sim2_results1 |> 
  dcast(variable + est ~ quant, value.var = "value") |>
  # uncomment for xtable
  subset(select = -variable) #|> 
  #xtable(digits = 4) 
  
```
Table 3

```{r}
setnames(x = sim2$CVM, old = names(sim2$CVM), new=names(sim2$KS))

sim2$CVM |> 
  setDT() |> 
  melt(id.vars = "id") |> 
  {\(x) x[, .(cvm_mean=mean(value), cvm_median=median(value)), .(variable)]}() |> 
  merge(x = _,
        y = {sim2$KS |> 
                setDT() |> 
                melt(id.vars = "id") |> 
                {\(x) x[, .(ks_mean=mean(value), ks_median=median(value)), .(variable)]}() },
        by = "variable") |> 
  transform(variable = factor(variable,
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CPBS (e)", "CBPS (e MQ)", "CBPS (e MP)", "CPBS (e P)", 
                           "CBPS (o)", "CBPS (o MQ)", "CBPS (o MP)", "CPBS (o P)"),
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CBPS (e)", "DPS (e MQ)", "DPS (e MD)", "DPS (e D)", 
                           "CBPS (o)", "DPS (o MQ)", "DPS (o MD)", "DPS (o D)"))) #|>
  ## uncomment for xtable
  #xtable() 
```

Table A4 in the Appendix

```{r}
setnames(x = sim1$CVM, old = names(sim1$CVM), new=names(sim1$KS))

sim1$CVM |> 
  setDT() |> 
  melt(id.vars = "id") |> 
  {\(x) x[, .(cvm_mean=mean(value), cvm_median=median(value)), .(variable)]}() |> 
  merge(x = _,
        y = {sim1$KS |> 
                setDT() |> 
                melt(id.vars = "id") |> 
                {\(x) x[, .(ks_mean=mean(value), ks_median=median(value)), .(variable)]}() },
        by = "variable") |> 
  transform(variable = factor(variable,
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CPBS (e)", "CBPS (e MQ)", "CBPS (e MP)", "CPBS (e P)", 
                           "CBPS (o)", "CBPS (o MQ)", "CBPS (o MP)", "CPBS (o P)"),
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CBPS (e)", "DPS (e MQ)", "DPS (e MD)", "DPS (e D)", 
                           "CBPS (o)", "DPS (o MQ)", "DPS (o MD)", "DPS (o D)"))) #|>
  ## uncomment for xtable
  #xtable()
```

Boxplots for highlights

Simulation 1

```{r}
# id, variable, value, est
sim1$ATE |> 
  melt(id.vars = "id", variable.name = "est") |> 
  transform(par = "ATE",
            quant = "") |> 
  rbind(
    sim1$QTE |> 
      subset(select = -variable) |> 
      transform(par = "QTE")
  ) |> 
  transform(quant = factor(quant, 
                           c("", "1", "2", "3", "4", "5"),
                           c("ATE", "QTE(0.10)", "QTE(0.25)", "QTE(0.50)", "QTE(0.75)", "QTE(0.90)")),
            est = factor(est,
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CPBS (e)", "CBPS (e MQ)", "CBPS (e MP)", "CPBS (e P)", 
                           "CBPS (o)", "CBPS (o MQ)", "CBPS (o MP)", "CPBS (o P)"),
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CBPS (e)", "DPS (e MQ)", "DPS (e MD)", "DPS (e D)", 
                           "CBPS (o)", "DPS (o MQ)", "DPS (o MD)", "DPS (o D)"))) |> 
  ggplot(data = _, aes(x = est, y = value)) +
  geom_boxplot() +
  facet_wrap(~quant, nrow = 1) +
  theme(axis.text.x = element_text(angle = 45, vjust=1,hjust=1, size = 6)) +
  geom_hline(yintercept = 10, color = "red", linetype="dashed") +
  labs(x = "Method", y = "Value", title = "Design 1: correctly specified models") -> p1

ggsave(plot = p1, filename = glue("../results/fig-sim-2-dbps-design-1.png"), width = 7, height = 5)
```
Simulation 2 

```{r}
sim2$ATE |> 
  melt(id.vars = "id", variable.name = "est") |> 
  transform(par = "ATE",
            quant = "") |> 
  rbind(
    sim2$QTE |> 
      subset(select = -variable) |> 
      transform(par = "QTE")
  ) |> 
  transform(quant = factor(quant, 
                           c("", "1", "2", "3", "4", "5"),
                           c("ATE", "QTE(0.10)", "QTE(0.25)", "QTE(0.50)", "QTE(0.75)", "QTE(0.90)")),
            est = factor(est,
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CPBS (e)", "CBPS (e MQ)", "CBPS (e MP)", "CPBS (e P)", 
                           "CBPS (o)", "CBPS (o MQ)", "CBPS (o MP)", "CPBS (o P)"),
                         c("IPS (exp)", "IPS (ind)", "IPS (proj)", 
                           "CBPS (e)", "DPS (e MQ)", "DPS (e MD)", "DPS (e D)", 
                           "CBPS (o)", "DPS (o MQ)", "DPS (o MD)", "DPS (o D)"))) |> 
  ggplot(data = _, aes(x = est, y = value)) +
  geom_boxplot() +
  facet_wrap(~quant, nrow = 1) +
  theme(axis.text.x = element_text(angle = 45, vjust=1,hjust=1, size = 6)) +
  geom_hline(yintercept = 10, color = "red", linetype="dashed") +
  labs(x = "Method", y = "Value", title = "Design 2: mis-specified models") -> p2

ggsave(plot = p2, filename = glue("../results/fig-sim-2-dbps-design-2.png"), width = 7, height = 5)
```

